name: Identifier Name
on:
  push:
    branches: [ Test1 ]

jobs:
  deploy:    
    runs-on: Zorin OS 16.1
    steps:
      - name: Reset Permissions before deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo chmod -R 755 /var/www/Raj2.com/

      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "*"
          target: "/var/www/Raj2.com/"

      - name: Reset Permissions after deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo chmod -R 755 /var/www/Raj2.com/
